config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
   #   delete "doses/:id",  to: "doses#destroy", as: :delete
   delete "cocktails/:id",  to: "cocktails#destroy", as: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :new, :create, :show] do
    resources :doses, only: [:new, :create]
  end
   resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
validates :name, presence: true, uniqueness: true
has_many :doses, dependent: :destroy
has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
validates :name, presence: true, uniqueness: true
has_many :doses
has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  def new
    @cocktail = Cocktail.new
  end
  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

    def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container mt-5">
<div class="row justify-content-center">

   <h1>All the cocktails<span class="btn btn-primary to_right_index"><%= link_to "New cocktail" , new_cocktail_path()%></span></h1>

</div>
<div class="cards">
<% @cocktails.each do |cocktail| %>
<div class="card-category d-flex justify-content-between bd-highlight align-items-end"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://placeimg.com/640/480/any" >
       <span class="align-self-start ml-5 text-lg"><%= cocktail.name.capitalize %></span>
<div class="m-2 btn btn-primary lg" ><%= link_to "Show" , cocktail_path(cocktail)%></div><div class="btn btn-danger lg m-2" >    <%= link_to "Delete", destroy_path(cocktail),
      method: :delete,
      data: { confirm: "Are you sure?" } %></div>

  </div>
<% end %>
</ul>
</div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
  <span class="btn btn-primary"><%= link_to "see all cocktails", cocktails_path %></span>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-8 col-md-8 mt-5">
<h1><%= @cocktail.name %><span class="btn btn-primary to_right_index"><%= link_to "see all cocktails", cocktails_path  %></span>
</h1>
<span class="btn btn-primary"><%= link_to "new dose", new_cocktail_dose_path(@cocktail) %></span>
</h1>

<% @cocktail.doses.each do |dose| %>
 <div class="card-product" style="position:relative">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg">
  <div class="card-product-infos">
    <span class="btn btn-danger to_right_show to_top"><%= link_to "X", dose_path(dose), {method: :delete,
      data: { confirm: "Are you sure?" }} %></span>
    <h2><%=   dose.ingredient.name %></h2>
    <p> <%=  dose.description %> </p>
  </div>
</div>

  <% end %>



</div>
</div>
</div>

app/views/doses/new.html.erb
<h1>Create a new dose</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description, class: "form-control" %>
  <%= f.association :ingredient, class: "form-control"%>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
  <span class="btn btn-primary"><%= link_to "see all cocktails", cocktails_path %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
</body>
  </body>
</html>